# Generated by Django 3.2.5 on 2021-07-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('parent_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_tree_app.category')),
                ('similarity', models.ManyToManyField(related_name='_category_tree_app_category_similarity_+', to='category_tree_app.Category')),
            ],
        ),
    ]
