# Generated by Django 3.2.5 on 2021-07-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_tree_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_category_id',
            new_name='parent_category',
        ),
    ]
