# Generated by Django 3.2.5 on 2021-07-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_tree_app', '0002_rename_parent_category_id_category_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='similarity',
            field=models.ManyToManyField(blank=True, related_name='_category_tree_app_category_similarity_+', to='category_tree_app.Category'),
        ),
    ]
