# Generated by Django 3.2.5 on 2021-07-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_tree_app', '0003_auto_20210722_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='similarity',
        ),
        migrations.AddField(
            model_name='category',
            name='similarities',
            field=models.ManyToManyField(blank=True, related_name='_category_tree_app_category_similarities_+', to='category_tree_app.Category'),
        ),
    ]
